#############################################################################
#   _________ ____________  ___                                             #
#  /   _____//  _____/\   \/  /  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  #
#  \_____  \/   \  ___ \     /   THE E(X)TENDED (S)ELFISH (G)ENE ALGORITHM  #
#  /        \    \_\  \/     \   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  #
# /_________/\________/___/\  \  https://github.com/squillero/sgx           #
#                           \_/                                             #
#                                                                           #
# Copyright © 2020 Giovanni Squillero  --  Licensed under Apache-2.0        #
#                                                                           #
#############################################################################

# Enable build config validation
version: ~> 1.0

language: python

branches:
  except:
    - /^exp\/.*/

install:
  - cd src
  - pip3 install --upgrade pytest
  - pip3 install .

jobs:
  include:
    - name: "Python 3.7 on Ubuntu Trusty 14.04"
      python: 3.7
      dist: trusty
    - name: "Python 3.8 on Ubuntu Xenial 16.04"
      python: 3.8
      dist: xenial
    - name: "Python 3.9 on Ubuntu Bionic 18.04"
      python: 3.9
      dist: bionic
    - name: "Bleeding edge Python on Ubuntu Focal 20.04"
      python: nightly
      dist: focal

    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 3.9 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.9
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      install:
        - cd src
        - pip3 install --upgrade pytest
        - pip3 install --user .

script:
  - pytest
