#############################################################################
#   _________ ____________  ___                                             #
#  /   _____//  _____/\   \/  /  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  #
#  \_____  \/   \  ___ \     /   THE E(X)TENDED (S)ELFISH (G)ENE ALGORITHM  #
#  /        \    \_\  \/     \   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  #
# /_________/\________/___/\  \  https://github.com/squillero/sgx           #
#                           \_/                                             #
#                                                                           #
# Copyright © 2020 Giovanni Squillero. Licensed under Apache-2.0.           #
#                                                                           #
#############################################################################

language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build

install:
  - pip install -r src/requirements.txt

script:
  - pytest